<?php
    $this->bootstrap();
    $this->jQuery();
    $this->backbone();
?>
<ul class="nav nav-tabs">
    <li>
        <a href="<?php echo $this->url('', array('action' => 'index')); ?>" title="<?php _e('Add client'); ?>">
            <?php _e('Add client'); ?>
        </a>
    </li>
    <li class="active">
        <a href="<?php echo $this->url('', array('action' => 'list')); ?>" title="<?php _e('Client list'); ?>">
            <?php _e('Client list');?>
        </a>
    </li>
</ul>
<div>
    <?php if (!$client) {
        echo '<p>' . __('No client infomation') . '</p>';
    } else { ?>
    <table class="table table-striped">
        <tr>
            <th><?php _e('Module name'); ?></th>
            <th><?php _e('Server name'); ?></th>
            <th><?php _e('Server Address'); ?></th>
            <th><?php _e('Client ID'); ?></th>
            <th><?php _e('Client Secret'); ?></th>
            <th><?php _e('Create Time'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach($client as $value) {?>
            <tr>
                <td><?php echo $value['module'] ;?></td>
                <td><?php echo $value['server'] ;?></td>
                <td><?php echo $value['server_host'] ;?></td>
                <td><?php echo $value['client_id'] ;?></td>
                <td><?php echo $value['client_secret'] ;?></td>
                <td><?php echo date('Y-m-d h:m:s', $value['time_create']) ;?></td>
                <td>
                    <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $value['id'])); ?>"><?php _e('Edit'); ?></a>
                    <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $value['id'])); ?>"><?php _e('Delete'); ?></a>
                </td>
            </tr>
        <?php }?>
        </table>
    <?php }?>
</div>